name: main
on:
    push:
        branches:
            - feature/deploy
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-northeast-2'

        steps:
            - name: Checkout source code.
              uses: actions/checkout@master

            - name: Upload binary to S3 Bucket
              env:
                  AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
            #   run: |
            #     aws s3 cp --recursive --region ap-northeast-2 ./* s3://${{ secrets.BUCKET_NAME }}
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --acl public-read
            #   env:
            #     AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}

            - name: Invalidate cache CloudFront
              uses: chetan/invalidate-cloudfront-action@master
              env:
                DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
                PATHS: '/index.html'
              continue-on-error: true