name: main
on:
    push:
        branches:
            - feature/deploy
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-northeast-2'

        steps:
            - name: Checkout source code.
              uses: actions/checkout@v3
              with:
                repository: 'feature/deploy'

            - name: Upload binary to S3 Bucket
              uses: jakejarvis/s3-sync-action@v3
              with:
                repository: 'feature/deploy'
                args: --acl public-read --exclude '*' --include 'index.html'
              env:
                AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}

            - name: Invalidate cache CloudFront
              uses: chetan/invalidate-cloudfront-action@v3
              with:
                repository: 'feature/deploy'
              env:
                DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
                PATHS: '/index.html'
              continue-on-error: true